2025-01-06 05:11:37,209 ERROR scheduler Exception in Enqueue Events for Site demo
Traceback (most recent call last):
  File "env/lib/python3.10/site-packages/redis/client.py", line 3911, in _execute_transaction
    response = self.parse_response(connection, '_')
  File "env/lib/python3.10/site-packages/redis/client.py", line 3977, in parse_response
    result = Redis.parse_response(
  File "env/lib/python3.10/site-packages/redis/client.py", line 915, in parse_response
    response = connection.read_response()
  File "env/lib/python3.10/site-packages/redis/connection.py", line 756, in read_response
    raise response
redis.exceptions.ExecAbortError: Transaction discarded because of previous errors.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "apps/frappe/frappe/utils/scheduler.py", line 78, in enqueue_events_for_site
    enqueue_events(site=site)
  File "apps/frappe/frappe/utils/scheduler.py", line 101, in enqueue_events
    frappe.get_doc("Scheduled Job Type", job_type.name).enqueue()
  File "apps/frappe/frappe/core/doctype/scheduled_job_type/scheduled_job_type.py", line 48, in enqueue
    enqueue(
  File "apps/frappe/frappe/utils/background_jobs.py", line 137, in enqueue
    return q.enqueue_call(
  File "env/lib/python3.10/site-packages/rq/queue.py", line 687, in enqueue_call
    return self.enqueue_job(job, pipeline=pipeline, at_front=at_front)
  File "env/lib/python3.10/site-packages/rq/queue.py", line 1013, in enqueue_job
    return self._enqueue_job(job, pipeline=pipeline, at_front=at_front)
  File "env/lib/python3.10/site-packages/rq/queue.py", line 1048, in _enqueue_job
    pipe.execute()
  File "env/lib/python3.10/site-packages/redis/client.py", line 4019, in execute
    return execute(conn, stack, raise_on_error)
  File "env/lib/python3.10/site-packages/redis/client.py", line 3914, in _execute_transaction
    raise errors[0][1]
  File "env/lib/python3.10/site-packages/redis/client.py", line 3904, in _execute_transaction
    self.parse_response(connection, '_')
  File "env/lib/python3.10/site-packages/redis/client.py", line 3977, in parse_response
    result = Redis.parse_response(
  File "env/lib/python3.10/site-packages/redis/client.py", line 915, in parse_response
    response = connection.read_response()
  File "env/lib/python3.10/site-packages/redis/connection.py", line 756, in read_response
    raise response
redis.exceptions.ResponseError: Command # 1 (SADD rq:queues rq:queue:home-frappe-frappe-bench:default) of pipeline caused error: MISCONF Redis is configured to save RDB snapshots, but it's currently unable to persist to disk. Commands that may modify the data set are disabled, because this instance is configured to report errors during writes if RDB snapshotting fails (stop-writes-on-bgsave-error option). Please check the Redis logs for details about the RDB error.

2025-01-06 05:12:37,488 ERROR scheduler Exception in Enqueue Events for Site demo
Traceback (most recent call last):
  File "env/lib/python3.10/site-packages/redis/client.py", line 3911, in _execute_transaction
    response = self.parse_response(connection, '_')
  File "env/lib/python3.10/site-packages/redis/client.py", line 3977, in parse_response
    result = Redis.parse_response(
  File "env/lib/python3.10/site-packages/redis/client.py", line 915, in parse_response
    response = connection.read_response()
  File "env/lib/python3.10/site-packages/redis/connection.py", line 756, in read_response
    raise response
redis.exceptions.ExecAbortError: Transaction discarded because of previous errors.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "apps/frappe/frappe/utils/scheduler.py", line 78, in enqueue_events_for_site
    enqueue_events(site=site)
  File "apps/frappe/frappe/utils/scheduler.py", line 101, in enqueue_events
    frappe.get_doc("Scheduled Job Type", job_type.name).enqueue()
  File "apps/frappe/frappe/core/doctype/scheduled_job_type/scheduled_job_type.py", line 48, in enqueue
    enqueue(
  File "apps/frappe/frappe/utils/background_jobs.py", line 137, in enqueue
    return q.enqueue_call(
  File "env/lib/python3.10/site-packages/rq/queue.py", line 687, in enqueue_call
    return self.enqueue_job(job, pipeline=pipeline, at_front=at_front)
  File "env/lib/python3.10/site-packages/rq/queue.py", line 1013, in enqueue_job
    return self._enqueue_job(job, pipeline=pipeline, at_front=at_front)
  File "env/lib/python3.10/site-packages/rq/queue.py", line 1048, in _enqueue_job
    pipe.execute()
  File "env/lib/python3.10/site-packages/redis/client.py", line 4019, in execute
    return execute(conn, stack, raise_on_error)
  File "env/lib/python3.10/site-packages/redis/client.py", line 3914, in _execute_transaction
    raise errors[0][1]
  File "env/lib/python3.10/site-packages/redis/client.py", line 3904, in _execute_transaction
    self.parse_response(connection, '_')
  File "env/lib/python3.10/site-packages/redis/client.py", line 3977, in parse_response
    result = Redis.parse_response(
  File "env/lib/python3.10/site-packages/redis/client.py", line 915, in parse_response
    response = connection.read_response()
  File "env/lib/python3.10/site-packages/redis/connection.py", line 756, in read_response
    raise response
redis.exceptions.ResponseError: Command # 1 (SADD rq:queues rq:queue:home-frappe-frappe-bench:default) of pipeline caused error: MISCONF Redis is configured to save RDB snapshots, but it's currently unable to persist to disk. Commands that may modify the data set are disabled, because this instance is configured to report errors during writes if RDB snapshotting fails (stop-writes-on-bgsave-error option). Please check the Redis logs for details about the RDB error.

2025-01-06 05:13:37,755 ERROR scheduler Exception in Enqueue Events for Site demo
Traceback (most recent call last):
  File "env/lib/python3.10/site-packages/redis/client.py", line 3911, in _execute_transaction
    response = self.parse_response(connection, '_')
  File "env/lib/python3.10/site-packages/redis/client.py", line 3977, in parse_response
    result = Redis.parse_response(
  File "env/lib/python3.10/site-packages/redis/client.py", line 915, in parse_response
    response = connection.read_response()
  File "env/lib/python3.10/site-packages/redis/connection.py", line 756, in read_response
    raise response
redis.exceptions.ExecAbortError: Transaction discarded because of previous errors.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "apps/frappe/frappe/utils/scheduler.py", line 78, in enqueue_events_for_site
    enqueue_events(site=site)
  File "apps/frappe/frappe/utils/scheduler.py", line 101, in enqueue_events
    frappe.get_doc("Scheduled Job Type", job_type.name).enqueue()
  File "apps/frappe/frappe/core/doctype/scheduled_job_type/scheduled_job_type.py", line 48, in enqueue
    enqueue(
  File "apps/frappe/frappe/utils/background_jobs.py", line 137, in enqueue
    return q.enqueue_call(
  File "env/lib/python3.10/site-packages/rq/queue.py", line 687, in enqueue_call
    return self.enqueue_job(job, pipeline=pipeline, at_front=at_front)
  File "env/lib/python3.10/site-packages/rq/queue.py", line 1013, in enqueue_job
    return self._enqueue_job(job, pipeline=pipeline, at_front=at_front)
  File "env/lib/python3.10/site-packages/rq/queue.py", line 1048, in _enqueue_job
    pipe.execute()
  File "env/lib/python3.10/site-packages/redis/client.py", line 4019, in execute
    return execute(conn, stack, raise_on_error)
  File "env/lib/python3.10/site-packages/redis/client.py", line 3914, in _execute_transaction
    raise errors[0][1]
  File "env/lib/python3.10/site-packages/redis/client.py", line 3904, in _execute_transaction
    self.parse_response(connection, '_')
  File "env/lib/python3.10/site-packages/redis/client.py", line 3977, in parse_response
    result = Redis.parse_response(
  File "env/lib/python3.10/site-packages/redis/client.py", line 915, in parse_response
    response = connection.read_response()
  File "env/lib/python3.10/site-packages/redis/connection.py", line 756, in read_response
    raise response
redis.exceptions.ResponseError: Command # 1 (SADD rq:queues rq:queue:home-frappe-frappe-bench:default) of pipeline caused error: MISCONF Redis is configured to save RDB snapshots, but it's currently unable to persist to disk. Commands that may modify the data set are disabled, because this instance is configured to report errors during writes if RDB snapshotting fails (stop-writes-on-bgsave-error option). Please check the Redis logs for details about the RDB error.

2025-01-06 05:14:37,987 ERROR scheduler Exception in Enqueue Events for Site demo
Traceback (most recent call last):
  File "env/lib/python3.10/site-packages/redis/client.py", line 3911, in _execute_transaction
    response = self.parse_response(connection, '_')
  File "env/lib/python3.10/site-packages/redis/client.py", line 3977, in parse_response
    result = Redis.parse_response(
  File "env/lib/python3.10/site-packages/redis/client.py", line 915, in parse_response
    response = connection.read_response()
  File "env/lib/python3.10/site-packages/redis/connection.py", line 756, in read_response
    raise response
redis.exceptions.ExecAbortError: Transaction discarded because of previous errors.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "apps/frappe/frappe/utils/scheduler.py", line 78, in enqueue_events_for_site
    enqueue_events(site=site)
  File "apps/frappe/frappe/utils/scheduler.py", line 101, in enqueue_events
    frappe.get_doc("Scheduled Job Type", job_type.name).enqueue()
  File "apps/frappe/frappe/core/doctype/scheduled_job_type/scheduled_job_type.py", line 48, in enqueue
    enqueue(
  File "apps/frappe/frappe/utils/background_jobs.py", line 137, in enqueue
    return q.enqueue_call(
  File "env/lib/python3.10/site-packages/rq/queue.py", line 687, in enqueue_call
    return self.enqueue_job(job, pipeline=pipeline, at_front=at_front)
  File "env/lib/python3.10/site-packages/rq/queue.py", line 1013, in enqueue_job
    return self._enqueue_job(job, pipeline=pipeline, at_front=at_front)
  File "env/lib/python3.10/site-packages/rq/queue.py", line 1048, in _enqueue_job
    pipe.execute()
  File "env/lib/python3.10/site-packages/redis/client.py", line 4019, in execute
    return execute(conn, stack, raise_on_error)
  File "env/lib/python3.10/site-packages/redis/client.py", line 3914, in _execute_transaction
    raise errors[0][1]
  File "env/lib/python3.10/site-packages/redis/client.py", line 3904, in _execute_transaction
    self.parse_response(connection, '_')
  File "env/lib/python3.10/site-packages/redis/client.py", line 3977, in parse_response
    result = Redis.parse_response(
  File "env/lib/python3.10/site-packages/redis/client.py", line 915, in parse_response
    response = connection.read_response()
  File "env/lib/python3.10/site-packages/redis/connection.py", line 756, in read_response
    raise response
redis.exceptions.ResponseError: Command # 1 (SADD rq:queues rq:queue:home-frappe-frappe-bench:default) of pipeline caused error: MISCONF Redis is configured to save RDB snapshots, but it's currently unable to persist to disk. Commands that may modify the data set are disabled, because this instance is configured to report errors during writes if RDB snapshotting fails (stop-writes-on-bgsave-error option). Please check the Redis logs for details about the RDB error.

2025-01-06 05:15:38,214 ERROR scheduler Exception in Enqueue Events for Site demo
Traceback (most recent call last):
  File "env/lib/python3.10/site-packages/redis/client.py", line 3911, in _execute_transaction
    response = self.parse_response(connection, '_')
  File "env/lib/python3.10/site-packages/redis/client.py", line 3977, in parse_response
    result = Redis.parse_response(
  File "env/lib/python3.10/site-packages/redis/client.py", line 915, in parse_response
    response = connection.read_response()
  File "env/lib/python3.10/site-packages/redis/connection.py", line 756, in read_response
    raise response
redis.exceptions.ExecAbortError: Transaction discarded because of previous errors.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "apps/frappe/frappe/utils/scheduler.py", line 78, in enqueue_events_for_site
    enqueue_events(site=site)
  File "apps/frappe/frappe/utils/scheduler.py", line 101, in enqueue_events
    frappe.get_doc("Scheduled Job Type", job_type.name).enqueue()
  File "apps/frappe/frappe/core/doctype/scheduled_job_type/scheduled_job_type.py", line 48, in enqueue
    enqueue(
  File "apps/frappe/frappe/utils/background_jobs.py", line 137, in enqueue
    return q.enqueue_call(
  File "env/lib/python3.10/site-packages/rq/queue.py", line 687, in enqueue_call
    return self.enqueue_job(job, pipeline=pipeline, at_front=at_front)
  File "env/lib/python3.10/site-packages/rq/queue.py", line 1013, in enqueue_job
    return self._enqueue_job(job, pipeline=pipeline, at_front=at_front)
  File "env/lib/python3.10/site-packages/rq/queue.py", line 1048, in _enqueue_job
    pipe.execute()
  File "env/lib/python3.10/site-packages/redis/client.py", line 4019, in execute
    return execute(conn, stack, raise_on_error)
  File "env/lib/python3.10/site-packages/redis/client.py", line 3914, in _execute_transaction
    raise errors[0][1]
  File "env/lib/python3.10/site-packages/redis/client.py", line 3904, in _execute_transaction
    self.parse_response(connection, '_')
  File "env/lib/python3.10/site-packages/redis/client.py", line 3977, in parse_response
    result = Redis.parse_response(
  File "env/lib/python3.10/site-packages/redis/client.py", line 915, in parse_response
    response = connection.read_response()
  File "env/lib/python3.10/site-packages/redis/connection.py", line 756, in read_response
    raise response
redis.exceptions.ResponseError: Command # 1 (SADD rq:queues rq:queue:home-frappe-frappe-bench:default) of pipeline caused error: MISCONF Redis is configured to save RDB snapshots, but it's currently unable to persist to disk. Commands that may modify the data set are disabled, because this instance is configured to report errors during writes if RDB snapshotting fails (stop-writes-on-bgsave-error option). Please check the Redis logs for details about the RDB error.

2025-01-06 05:16:38,421 ERROR scheduler Exception in Enqueue Events for Site demo
Traceback (most recent call last):
  File "env/lib/python3.10/site-packages/redis/client.py", line 3911, in _execute_transaction
    response = self.parse_response(connection, '_')
  File "env/lib/python3.10/site-packages/redis/client.py", line 3977, in parse_response
    result = Redis.parse_response(
  File "env/lib/python3.10/site-packages/redis/client.py", line 915, in parse_response
    response = connection.read_response()
  File "env/lib/python3.10/site-packages/redis/connection.py", line 756, in read_response
    raise response
redis.exceptions.ExecAbortError: Transaction discarded because of previous errors.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "apps/frappe/frappe/utils/scheduler.py", line 78, in enqueue_events_for_site
    enqueue_events(site=site)
  File "apps/frappe/frappe/utils/scheduler.py", line 101, in enqueue_events
    frappe.get_doc("Scheduled Job Type", job_type.name).enqueue()
  File "apps/frappe/frappe/core/doctype/scheduled_job_type/scheduled_job_type.py", line 48, in enqueue
    enqueue(
  File "apps/frappe/frappe/utils/background_jobs.py", line 137, in enqueue
    return q.enqueue_call(
  File "env/lib/python3.10/site-packages/rq/queue.py", line 687, in enqueue_call
    return self.enqueue_job(job, pipeline=pipeline, at_front=at_front)
  File "env/lib/python3.10/site-packages/rq/queue.py", line 1013, in enqueue_job
    return self._enqueue_job(job, pipeline=pipeline, at_front=at_front)
  File "env/lib/python3.10/site-packages/rq/queue.py", line 1048, in _enqueue_job
    pipe.execute()
  File "env/lib/python3.10/site-packages/redis/client.py", line 4019, in execute
    return execute(conn, stack, raise_on_error)
  File "env/lib/python3.10/site-packages/redis/client.py", line 3914, in _execute_transaction
    raise errors[0][1]
  File "env/lib/python3.10/site-packages/redis/client.py", line 3904, in _execute_transaction
    self.parse_response(connection, '_')
  File "env/lib/python3.10/site-packages/redis/client.py", line 3977, in parse_response
    result = Redis.parse_response(
  File "env/lib/python3.10/site-packages/redis/client.py", line 915, in parse_response
    response = connection.read_response()
  File "env/lib/python3.10/site-packages/redis/connection.py", line 756, in read_response
    raise response
redis.exceptions.ResponseError: Command # 1 (SADD rq:queues rq:queue:home-frappe-frappe-bench:default) of pipeline caused error: MISCONF Redis is configured to save RDB snapshots, but it's currently unable to persist to disk. Commands that may modify the data set are disabled, because this instance is configured to report errors during writes if RDB snapshotting fails (stop-writes-on-bgsave-error option). Please check the Redis logs for details about the RDB error.

2025-01-06 05:17:38,551 ERROR scheduler Exception in Enqueue Events for Site demo
Traceback (most recent call last):
  File "env/lib/python3.10/site-packages/redis/client.py", line 3911, in _execute_transaction
    response = self.parse_response(connection, '_')
  File "env/lib/python3.10/site-packages/redis/client.py", line 3977, in parse_response
    result = Redis.parse_response(
  File "env/lib/python3.10/site-packages/redis/client.py", line 915, in parse_response
    response = connection.read_response()
  File "env/lib/python3.10/site-packages/redis/connection.py", line 756, in read_response
    raise response
redis.exceptions.ExecAbortError: Transaction discarded because of previous errors.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "apps/frappe/frappe/utils/scheduler.py", line 78, in enqueue_events_for_site
    enqueue_events(site=site)
  File "apps/frappe/frappe/utils/scheduler.py", line 101, in enqueue_events
    frappe.get_doc("Scheduled Job Type", job_type.name).enqueue()
  File "apps/frappe/frappe/core/doctype/scheduled_job_type/scheduled_job_type.py", line 48, in enqueue
    enqueue(
  File "apps/frappe/frappe/utils/background_jobs.py", line 137, in enqueue
    return q.enqueue_call(
  File "env/lib/python3.10/site-packages/rq/queue.py", line 687, in enqueue_call
    return self.enqueue_job(job, pipeline=pipeline, at_front=at_front)
  File "env/lib/python3.10/site-packages/rq/queue.py", line 1013, in enqueue_job
    return self._enqueue_job(job, pipeline=pipeline, at_front=at_front)
  File "env/lib/python3.10/site-packages/rq/queue.py", line 1048, in _enqueue_job
    pipe.execute()
  File "env/lib/python3.10/site-packages/redis/client.py", line 4019, in execute
    return execute(conn, stack, raise_on_error)
  File "env/lib/python3.10/site-packages/redis/client.py", line 3914, in _execute_transaction
    raise errors[0][1]
  File "env/lib/python3.10/site-packages/redis/client.py", line 3904, in _execute_transaction
    self.parse_response(connection, '_')
  File "env/lib/python3.10/site-packages/redis/client.py", line 3977, in parse_response
    result = Redis.parse_response(
  File "env/lib/python3.10/site-packages/redis/client.py", line 915, in parse_response
    response = connection.read_response()
  File "env/lib/python3.10/site-packages/redis/connection.py", line 756, in read_response
    raise response
redis.exceptions.ResponseError: Command # 1 (SADD rq:queues rq:queue:home-frappe-frappe-bench:default) of pipeline caused error: MISCONF Redis is configured to save RDB snapshots, but it's currently unable to persist to disk. Commands that may modify the data set are disabled, because this instance is configured to report errors during writes if RDB snapshotting fails (stop-writes-on-bgsave-error option). Please check the Redis logs for details about the RDB error.

2025-01-06 05:18:38,676 ERROR scheduler Exception in Enqueue Events for Site demo
Traceback (most recent call last):
  File "apps/frappe/frappe/utils/scheduler.py", line 78, in enqueue_events_for_site
    enqueue_events(site=site)
  File "apps/frappe/frappe/utils/scheduler.py", line 96, in enqueue_events
    queued_jobs = get_jobs(site=site, key="job_type").get(site) or []
  File "apps/frappe/frappe/utils/background_jobs.py", line 299, in get_jobs
    jobs = q.jobs + get_running_jobs_in_queue(q)
  File "apps/frappe/frappe/utils/background_jobs.py", line 336, in get_running_jobs_in_queue
    workers = get_workers(queue)
  File "apps/frappe/frappe/utils/background_jobs.py", line 328, in get_workers
    return Worker.all(queue=queue)
  File "env/lib/python3.10/site-packages/rq/worker.py", line 257, in all
    workers = [
  File "env/lib/python3.10/site-packages/rq/worker.py", line 258, in <listcomp>
    cls.find_by_key(
  File "env/lib/python3.10/site-packages/rq/worker.py", line 671, in find_by_key
    connection.srem(cls.redis_workers_keys, worker_key)
  File "env/lib/python3.10/site-packages/redis/client.py", line 2305, in srem
    return self.execute_command('SREM', name, *values)
  File "env/lib/python3.10/site-packages/redis/client.py", line 901, in execute_command
    return self.parse_response(conn, command_name, **options)
  File "env/lib/python3.10/site-packages/redis/client.py", line 915, in parse_response
    response = connection.read_response()
  File "env/lib/python3.10/site-packages/redis/connection.py", line 756, in read_response
    raise response
redis.exceptions.ResponseError: MISCONF Redis is configured to save RDB snapshots, but it's currently unable to persist to disk. Commands that may modify the data set are disabled, because this instance is configured to report errors during writes if RDB snapshotting fails (stop-writes-on-bgsave-error option). Please check the Redis logs for details about the RDB error.

2025-01-06 05:19:38,816 ERROR scheduler Exception in Enqueue Events for Site demo
Traceback (most recent call last):
  File "apps/frappe/frappe/utils/scheduler.py", line 78, in enqueue_events_for_site
    enqueue_events(site=site)
  File "apps/frappe/frappe/utils/scheduler.py", line 96, in enqueue_events
    queued_jobs = get_jobs(site=site, key="job_type").get(site) or []
  File "apps/frappe/frappe/utils/background_jobs.py", line 299, in get_jobs
    jobs = q.jobs + get_running_jobs_in_queue(q)
  File "apps/frappe/frappe/utils/background_jobs.py", line 336, in get_running_jobs_in_queue
    workers = get_workers(queue)
  File "apps/frappe/frappe/utils/background_jobs.py", line 328, in get_workers
    return Worker.all(queue=queue)
  File "env/lib/python3.10/site-packages/rq/worker.py", line 257, in all
    workers = [
  File "env/lib/python3.10/site-packages/rq/worker.py", line 258, in <listcomp>
    cls.find_by_key(
  File "env/lib/python3.10/site-packages/rq/worker.py", line 671, in find_by_key
    connection.srem(cls.redis_workers_keys, worker_key)
  File "env/lib/python3.10/site-packages/redis/client.py", line 2305, in srem
    return self.execute_command('SREM', name, *values)
  File "env/lib/python3.10/site-packages/redis/client.py", line 901, in execute_command
    return self.parse_response(conn, command_name, **options)
  File "env/lib/python3.10/site-packages/redis/client.py", line 915, in parse_response
    response = connection.read_response()
  File "env/lib/python3.10/site-packages/redis/connection.py", line 756, in read_response
    raise response
redis.exceptions.ResponseError: MISCONF Redis is configured to save RDB snapshots, but it's currently unable to persist to disk. Commands that may modify the data set are disabled, because this instance is configured to report errors during writes if RDB snapshotting fails (stop-writes-on-bgsave-error option). Please check the Redis logs for details about the RDB error.

2025-01-06 05:20:38,934 ERROR scheduler Exception in Enqueue Events for Site demo
Traceback (most recent call last):
  File "apps/frappe/frappe/utils/scheduler.py", line 78, in enqueue_events_for_site
    enqueue_events(site=site)
  File "apps/frappe/frappe/utils/scheduler.py", line 96, in enqueue_events
    queued_jobs = get_jobs(site=site, key="job_type").get(site) or []
  File "apps/frappe/frappe/utils/background_jobs.py", line 299, in get_jobs
    jobs = q.jobs + get_running_jobs_in_queue(q)
  File "apps/frappe/frappe/utils/background_jobs.py", line 336, in get_running_jobs_in_queue
    workers = get_workers(queue)
  File "apps/frappe/frappe/utils/background_jobs.py", line 328, in get_workers
    return Worker.all(queue=queue)
  File "env/lib/python3.10/site-packages/rq/worker.py", line 257, in all
    workers = [
  File "env/lib/python3.10/site-packages/rq/worker.py", line 258, in <listcomp>
    cls.find_by_key(
  File "env/lib/python3.10/site-packages/rq/worker.py", line 671, in find_by_key
    connection.srem(cls.redis_workers_keys, worker_key)
  File "env/lib/python3.10/site-packages/redis/client.py", line 2305, in srem
    return self.execute_command('SREM', name, *values)
  File "env/lib/python3.10/site-packages/redis/client.py", line 901, in execute_command
    return self.parse_response(conn, command_name, **options)
  File "env/lib/python3.10/site-packages/redis/client.py", line 915, in parse_response
    response = connection.read_response()
  File "env/lib/python3.10/site-packages/redis/connection.py", line 756, in read_response
    raise response
redis.exceptions.ResponseError: MISCONF Redis is configured to save RDB snapshots, but it's currently unable to persist to disk. Commands that may modify the data set are disabled, because this instance is configured to report errors during writes if RDB snapshotting fails (stop-writes-on-bgsave-error option). Please check the Redis logs for details about the RDB error.

2025-01-06 05:21:39,105 ERROR scheduler Exception in Enqueue Events for Site demo
Traceback (most recent call last):
  File "apps/frappe/frappe/utils/scheduler.py", line 78, in enqueue_events_for_site
    enqueue_events(site=site)
  File "apps/frappe/frappe/utils/scheduler.py", line 96, in enqueue_events
    queued_jobs = get_jobs(site=site, key="job_type").get(site) or []
  File "apps/frappe/frappe/utils/background_jobs.py", line 299, in get_jobs
    jobs = q.jobs + get_running_jobs_in_queue(q)
  File "apps/frappe/frappe/utils/background_jobs.py", line 336, in get_running_jobs_in_queue
    workers = get_workers(queue)
  File "apps/frappe/frappe/utils/background_jobs.py", line 328, in get_workers
    return Worker.all(queue=queue)
  File "env/lib/python3.10/site-packages/rq/worker.py", line 257, in all
    workers = [
  File "env/lib/python3.10/site-packages/rq/worker.py", line 258, in <listcomp>
    cls.find_by_key(
  File "env/lib/python3.10/site-packages/rq/worker.py", line 671, in find_by_key
    connection.srem(cls.redis_workers_keys, worker_key)
  File "env/lib/python3.10/site-packages/redis/client.py", line 2305, in srem
    return self.execute_command('SREM', name, *values)
  File "env/lib/python3.10/site-packages/redis/client.py", line 901, in execute_command
    return self.parse_response(conn, command_name, **options)
  File "env/lib/python3.10/site-packages/redis/client.py", line 915, in parse_response
    response = connection.read_response()
  File "env/lib/python3.10/site-packages/redis/connection.py", line 756, in read_response
    raise response
redis.exceptions.ResponseError: MISCONF Redis is configured to save RDB snapshots, but it's currently unable to persist to disk. Commands that may modify the data set are disabled, because this instance is configured to report errors during writes if RDB snapshotting fails (stop-writes-on-bgsave-error option). Please check the Redis logs for details about the RDB error.

2025-01-06 05:22:39,226 ERROR scheduler Exception in Enqueue Events for Site demo
Traceback (most recent call last):
  File "apps/frappe/frappe/utils/scheduler.py", line 78, in enqueue_events_for_site
    enqueue_events(site=site)
  File "apps/frappe/frappe/utils/scheduler.py", line 96, in enqueue_events
    queued_jobs = get_jobs(site=site, key="job_type").get(site) or []
  File "apps/frappe/frappe/utils/background_jobs.py", line 299, in get_jobs
    jobs = q.jobs + get_running_jobs_in_queue(q)
  File "apps/frappe/frappe/utils/background_jobs.py", line 336, in get_running_jobs_in_queue
    workers = get_workers(queue)
  File "apps/frappe/frappe/utils/background_jobs.py", line 328, in get_workers
    return Worker.all(queue=queue)
  File "env/lib/python3.10/site-packages/rq/worker.py", line 257, in all
    workers = [
  File "env/lib/python3.10/site-packages/rq/worker.py", line 258, in <listcomp>
    cls.find_by_key(
  File "env/lib/python3.10/site-packages/rq/worker.py", line 671, in find_by_key
    connection.srem(cls.redis_workers_keys, worker_key)
  File "env/lib/python3.10/site-packages/redis/client.py", line 2305, in srem
    return self.execute_command('SREM', name, *values)
  File "env/lib/python3.10/site-packages/redis/client.py", line 901, in execute_command
    return self.parse_response(conn, command_name, **options)
  File "env/lib/python3.10/site-packages/redis/client.py", line 915, in parse_response
    response = connection.read_response()
  File "env/lib/python3.10/site-packages/redis/connection.py", line 756, in read_response
    raise response
redis.exceptions.ResponseError: MISCONF Redis is configured to save RDB snapshots, but it's currently unable to persist to disk. Commands that may modify the data set are disabled, because this instance is configured to report errors during writes if RDB snapshotting fails (stop-writes-on-bgsave-error option). Please check the Redis logs for details about the RDB error.

2025-01-06 05:23:39,496 ERROR scheduler Exception in Enqueue Events for Site demo
Traceback (most recent call last):
  File "apps/frappe/frappe/utils/scheduler.py", line 78, in enqueue_events_for_site
    enqueue_events(site=site)
  File "apps/frappe/frappe/utils/scheduler.py", line 96, in enqueue_events
    queued_jobs = get_jobs(site=site, key="job_type").get(site) or []
  File "apps/frappe/frappe/utils/background_jobs.py", line 299, in get_jobs
    jobs = q.jobs + get_running_jobs_in_queue(q)
  File "apps/frappe/frappe/utils/background_jobs.py", line 336, in get_running_jobs_in_queue
    workers = get_workers(queue)
  File "apps/frappe/frappe/utils/background_jobs.py", line 328, in get_workers
    return Worker.all(queue=queue)
  File "env/lib/python3.10/site-packages/rq/worker.py", line 257, in all
    workers = [
  File "env/lib/python3.10/site-packages/rq/worker.py", line 258, in <listcomp>
    cls.find_by_key(
  File "env/lib/python3.10/site-packages/rq/worker.py", line 671, in find_by_key
    connection.srem(cls.redis_workers_keys, worker_key)
  File "env/lib/python3.10/site-packages/redis/client.py", line 2305, in srem
    return self.execute_command('SREM', name, *values)
  File "env/lib/python3.10/site-packages/redis/client.py", line 901, in execute_command
    return self.parse_response(conn, command_name, **options)
  File "env/lib/python3.10/site-packages/redis/client.py", line 915, in parse_response
    response = connection.read_response()
  File "env/lib/python3.10/site-packages/redis/connection.py", line 756, in read_response
    raise response
redis.exceptions.ResponseError: MISCONF Redis is configured to save RDB snapshots, but it's currently unable to persist to disk. Commands that may modify the data set are disabled, because this instance is configured to report errors during writes if RDB snapshotting fails (stop-writes-on-bgsave-error option). Please check the Redis logs for details about the RDB error.

2025-01-06 05:24:39,553 ERROR scheduler Exception in Enqueue Events for Site demo
Traceback (most recent call last):
  File "apps/frappe/frappe/utils/scheduler.py", line 78, in enqueue_events_for_site
    enqueue_events(site=site)
  File "apps/frappe/frappe/utils/scheduler.py", line 96, in enqueue_events
    queued_jobs = get_jobs(site=site, key="job_type").get(site) or []
  File "apps/frappe/frappe/utils/background_jobs.py", line 299, in get_jobs
    jobs = q.jobs + get_running_jobs_in_queue(q)
  File "apps/frappe/frappe/utils/background_jobs.py", line 336, in get_running_jobs_in_queue
    workers = get_workers(queue)
  File "apps/frappe/frappe/utils/background_jobs.py", line 328, in get_workers
    return Worker.all(queue=queue)
  File "env/lib/python3.10/site-packages/rq/worker.py", line 257, in all
    workers = [
  File "env/lib/python3.10/site-packages/rq/worker.py", line 258, in <listcomp>
    cls.find_by_key(
  File "env/lib/python3.10/site-packages/rq/worker.py", line 671, in find_by_key
    connection.srem(cls.redis_workers_keys, worker_key)
  File "env/lib/python3.10/site-packages/redis/client.py", line 2305, in srem
    return self.execute_command('SREM', name, *values)
  File "env/lib/python3.10/site-packages/redis/client.py", line 901, in execute_command
    return self.parse_response(conn, command_name, **options)
  File "env/lib/python3.10/site-packages/redis/client.py", line 915, in parse_response
    response = connection.read_response()
  File "env/lib/python3.10/site-packages/redis/connection.py", line 756, in read_response
    raise response
redis.exceptions.ResponseError: MISCONF Redis is configured to save RDB snapshots, but it's currently unable to persist to disk. Commands that may modify the data set are disabled, because this instance is configured to report errors during writes if RDB snapshotting fails (stop-writes-on-bgsave-error option). Please check the Redis logs for details about the RDB error.

2025-01-06 05:25:39,686 ERROR scheduler Exception in Enqueue Events for Site demo
Traceback (most recent call last):
  File "apps/frappe/frappe/utils/scheduler.py", line 78, in enqueue_events_for_site
    enqueue_events(site=site)
  File "apps/frappe/frappe/utils/scheduler.py", line 96, in enqueue_events
    queued_jobs = get_jobs(site=site, key="job_type").get(site) or []
  File "apps/frappe/frappe/utils/background_jobs.py", line 299, in get_jobs
    jobs = q.jobs + get_running_jobs_in_queue(q)
  File "apps/frappe/frappe/utils/background_jobs.py", line 336, in get_running_jobs_in_queue
    workers = get_workers(queue)
  File "apps/frappe/frappe/utils/background_jobs.py", line 328, in get_workers
    return Worker.all(queue=queue)
  File "env/lib/python3.10/site-packages/rq/worker.py", line 257, in all
    workers = [
  File "env/lib/python3.10/site-packages/rq/worker.py", line 258, in <listcomp>
    cls.find_by_key(
  File "env/lib/python3.10/site-packages/rq/worker.py", line 671, in find_by_key
    connection.srem(cls.redis_workers_keys, worker_key)
  File "env/lib/python3.10/site-packages/redis/client.py", line 2305, in srem
    return self.execute_command('SREM', name, *values)
  File "env/lib/python3.10/site-packages/redis/client.py", line 901, in execute_command
    return self.parse_response(conn, command_name, **options)
  File "env/lib/python3.10/site-packages/redis/client.py", line 915, in parse_response
    response = connection.read_response()
  File "env/lib/python3.10/site-packages/redis/connection.py", line 756, in read_response
    raise response
redis.exceptions.ResponseError: MISCONF Redis is configured to save RDB snapshots, but it's currently unable to persist to disk. Commands that may modify the data set are disabled, because this instance is configured to report errors during writes if RDB snapshotting fails (stop-writes-on-bgsave-error option). Please check the Redis logs for details about the RDB error.

2025-01-06 05:26:39,847 ERROR scheduler Exception in Enqueue Events for Site demo
Traceback (most recent call last):
  File "apps/frappe/frappe/utils/scheduler.py", line 78, in enqueue_events_for_site
    enqueue_events(site=site)
  File "apps/frappe/frappe/utils/scheduler.py", line 96, in enqueue_events
    queued_jobs = get_jobs(site=site, key="job_type").get(site) or []
  File "apps/frappe/frappe/utils/background_jobs.py", line 299, in get_jobs
    jobs = q.jobs + get_running_jobs_in_queue(q)
  File "apps/frappe/frappe/utils/background_jobs.py", line 336, in get_running_jobs_in_queue
    workers = get_workers(queue)
  File "apps/frappe/frappe/utils/background_jobs.py", line 328, in get_workers
    return Worker.all(queue=queue)
  File "env/lib/python3.10/site-packages/rq/worker.py", line 257, in all
    workers = [
  File "env/lib/python3.10/site-packages/rq/worker.py", line 258, in <listcomp>
    cls.find_by_key(
  File "env/lib/python3.10/site-packages/rq/worker.py", line 671, in find_by_key
    connection.srem(cls.redis_workers_keys, worker_key)
  File "env/lib/python3.10/site-packages/redis/client.py", line 2305, in srem
    return self.execute_command('SREM', name, *values)
  File "env/lib/python3.10/site-packages/redis/client.py", line 901, in execute_command
    return self.parse_response(conn, command_name, **options)
  File "env/lib/python3.10/site-packages/redis/client.py", line 915, in parse_response
    response = connection.read_response()
  File "env/lib/python3.10/site-packages/redis/connection.py", line 756, in read_response
    raise response
redis.exceptions.ResponseError: MISCONF Redis is configured to save RDB snapshots, but it's currently unable to persist to disk. Commands that may modify the data set are disabled, because this instance is configured to report errors during writes if RDB snapshotting fails (stop-writes-on-bgsave-error option). Please check the Redis logs for details about the RDB error.

2025-01-06 05:27:40,003 ERROR scheduler Exception in Enqueue Events for Site demo
Traceback (most recent call last):
  File "apps/frappe/frappe/utils/scheduler.py", line 78, in enqueue_events_for_site
    enqueue_events(site=site)
  File "apps/frappe/frappe/utils/scheduler.py", line 96, in enqueue_events
    queued_jobs = get_jobs(site=site, key="job_type").get(site) or []
  File "apps/frappe/frappe/utils/background_jobs.py", line 299, in get_jobs
    jobs = q.jobs + get_running_jobs_in_queue(q)
  File "apps/frappe/frappe/utils/background_jobs.py", line 336, in get_running_jobs_in_queue
    workers = get_workers(queue)
  File "apps/frappe/frappe/utils/background_jobs.py", line 328, in get_workers
    return Worker.all(queue=queue)
  File "env/lib/python3.10/site-packages/rq/worker.py", line 257, in all
    workers = [
  File "env/lib/python3.10/site-packages/rq/worker.py", line 258, in <listcomp>
    cls.find_by_key(
  File "env/lib/python3.10/site-packages/rq/worker.py", line 671, in find_by_key
    connection.srem(cls.redis_workers_keys, worker_key)
  File "env/lib/python3.10/site-packages/redis/client.py", line 2305, in srem
    return self.execute_command('SREM', name, *values)
  File "env/lib/python3.10/site-packages/redis/client.py", line 901, in execute_command
    return self.parse_response(conn, command_name, **options)
  File "env/lib/python3.10/site-packages/redis/client.py", line 915, in parse_response
    response = connection.read_response()
  File "env/lib/python3.10/site-packages/redis/connection.py", line 756, in read_response
    raise response
redis.exceptions.ResponseError: MISCONF Redis is configured to save RDB snapshots, but it's currently unable to persist to disk. Commands that may modify the data set are disabled, because this instance is configured to report errors during writes if RDB snapshotting fails (stop-writes-on-bgsave-error option). Please check the Redis logs for details about the RDB error.

2025-01-06 05:28:40,173 ERROR scheduler Exception in Enqueue Events for Site demo
Traceback (most recent call last):
  File "apps/frappe/frappe/utils/scheduler.py", line 78, in enqueue_events_for_site
    enqueue_events(site=site)
  File "apps/frappe/frappe/utils/scheduler.py", line 96, in enqueue_events
    queued_jobs = get_jobs(site=site, key="job_type").get(site) or []
  File "apps/frappe/frappe/utils/background_jobs.py", line 299, in get_jobs
    jobs = q.jobs + get_running_jobs_in_queue(q)
  File "apps/frappe/frappe/utils/background_jobs.py", line 336, in get_running_jobs_in_queue
    workers = get_workers(queue)
  File "apps/frappe/frappe/utils/background_jobs.py", line 328, in get_workers
    return Worker.all(queue=queue)
  File "env/lib/python3.10/site-packages/rq/worker.py", line 257, in all
    workers = [
  File "env/lib/python3.10/site-packages/rq/worker.py", line 258, in <listcomp>
    cls.find_by_key(
  File "env/lib/python3.10/site-packages/rq/worker.py", line 671, in find_by_key
    connection.srem(cls.redis_workers_keys, worker_key)
  File "env/lib/python3.10/site-packages/redis/client.py", line 2305, in srem
    return self.execute_command('SREM', name, *values)
  File "env/lib/python3.10/site-packages/redis/client.py", line 901, in execute_command
    return self.parse_response(conn, command_name, **options)
  File "env/lib/python3.10/site-packages/redis/client.py", line 915, in parse_response
    response = connection.read_response()
  File "env/lib/python3.10/site-packages/redis/connection.py", line 756, in read_response
    raise response
redis.exceptions.ResponseError: MISCONF Redis is configured to save RDB snapshots, but it's currently unable to persist to disk. Commands that may modify the data set are disabled, because this instance is configured to report errors during writes if RDB snapshotting fails (stop-writes-on-bgsave-error option). Please check the Redis logs for details about the RDB error.

2025-01-06 05:29:40,371 ERROR scheduler Exception in Enqueue Events for Site demo
Traceback (most recent call last):
  File "apps/frappe/frappe/utils/scheduler.py", line 78, in enqueue_events_for_site
    enqueue_events(site=site)
  File "apps/frappe/frappe/utils/scheduler.py", line 96, in enqueue_events
    queued_jobs = get_jobs(site=site, key="job_type").get(site) or []
  File "apps/frappe/frappe/utils/background_jobs.py", line 299, in get_jobs
    jobs = q.jobs + get_running_jobs_in_queue(q)
  File "apps/frappe/frappe/utils/background_jobs.py", line 336, in get_running_jobs_in_queue
    workers = get_workers(queue)
  File "apps/frappe/frappe/utils/background_jobs.py", line 328, in get_workers
    return Worker.all(queue=queue)
  File "env/lib/python3.10/site-packages/rq/worker.py", line 257, in all
    workers = [
  File "env/lib/python3.10/site-packages/rq/worker.py", line 258, in <listcomp>
    cls.find_by_key(
  File "env/lib/python3.10/site-packages/rq/worker.py", line 671, in find_by_key
    connection.srem(cls.redis_workers_keys, worker_key)
  File "env/lib/python3.10/site-packages/redis/client.py", line 2305, in srem
    return self.execute_command('SREM', name, *values)
  File "env/lib/python3.10/site-packages/redis/client.py", line 901, in execute_command
    return self.parse_response(conn, command_name, **options)
  File "env/lib/python3.10/site-packages/redis/client.py", line 915, in parse_response
    response = connection.read_response()
  File "env/lib/python3.10/site-packages/redis/connection.py", line 756, in read_response
    raise response
redis.exceptions.ResponseError: MISCONF Redis is configured to save RDB snapshots, but it's currently unable to persist to disk. Commands that may modify the data set are disabled, because this instance is configured to report errors during writes if RDB snapshotting fails (stop-writes-on-bgsave-error option). Please check the Redis logs for details about the RDB error.

2025-01-06 05:30:40,572 ERROR scheduler Exception in Enqueue Events for Site demo
Traceback (most recent call last):
  File "apps/frappe/frappe/utils/scheduler.py", line 78, in enqueue_events_for_site
    enqueue_events(site=site)
  File "apps/frappe/frappe/utils/scheduler.py", line 96, in enqueue_events
    queued_jobs = get_jobs(site=site, key="job_type").get(site) or []
  File "apps/frappe/frappe/utils/background_jobs.py", line 299, in get_jobs
    jobs = q.jobs + get_running_jobs_in_queue(q)
  File "apps/frappe/frappe/utils/background_jobs.py", line 336, in get_running_jobs_in_queue
    workers = get_workers(queue)
  File "apps/frappe/frappe/utils/background_jobs.py", line 328, in get_workers
    return Worker.all(queue=queue)
  File "env/lib/python3.10/site-packages/rq/worker.py", line 257, in all
    workers = [
  File "env/lib/python3.10/site-packages/rq/worker.py", line 258, in <listcomp>
    cls.find_by_key(
  File "env/lib/python3.10/site-packages/rq/worker.py", line 671, in find_by_key
    connection.srem(cls.redis_workers_keys, worker_key)
  File "env/lib/python3.10/site-packages/redis/client.py", line 2305, in srem
    return self.execute_command('SREM', name, *values)
  File "env/lib/python3.10/site-packages/redis/client.py", line 901, in execute_command
    return self.parse_response(conn, command_name, **options)
  File "env/lib/python3.10/site-packages/redis/client.py", line 915, in parse_response
    response = connection.read_response()
  File "env/lib/python3.10/site-packages/redis/connection.py", line 756, in read_response
    raise response
redis.exceptions.ResponseError: MISCONF Redis is configured to save RDB snapshots, but it's currently unable to persist to disk. Commands that may modify the data set are disabled, because this instance is configured to report errors during writes if RDB snapshotting fails (stop-writes-on-bgsave-error option). Please check the Redis logs for details about the RDB error.

2025-01-06 05:31:40,647 ERROR scheduler Exception in Enqueue Events for Site demo
Traceback (most recent call last):
  File "apps/frappe/frappe/utils/scheduler.py", line 78, in enqueue_events_for_site
    enqueue_events(site=site)
  File "apps/frappe/frappe/utils/scheduler.py", line 96, in enqueue_events
    queued_jobs = get_jobs(site=site, key="job_type").get(site) or []
  File "apps/frappe/frappe/utils/background_jobs.py", line 299, in get_jobs
    jobs = q.jobs + get_running_jobs_in_queue(q)
  File "apps/frappe/frappe/utils/background_jobs.py", line 336, in get_running_jobs_in_queue
    workers = get_workers(queue)
  File "apps/frappe/frappe/utils/background_jobs.py", line 328, in get_workers
    return Worker.all(queue=queue)
  File "env/lib/python3.10/site-packages/rq/worker.py", line 257, in all
    workers = [
  File "env/lib/python3.10/site-packages/rq/worker.py", line 258, in <listcomp>
    cls.find_by_key(
  File "env/lib/python3.10/site-packages/rq/worker.py", line 671, in find_by_key
    connection.srem(cls.redis_workers_keys, worker_key)
  File "env/lib/python3.10/site-packages/redis/client.py", line 2305, in srem
    return self.execute_command('SREM', name, *values)
  File "env/lib/python3.10/site-packages/redis/client.py", line 901, in execute_command
    return self.parse_response(conn, command_name, **options)
  File "env/lib/python3.10/site-packages/redis/client.py", line 915, in parse_response
    response = connection.read_response()
  File "env/lib/python3.10/site-packages/redis/connection.py", line 756, in read_response
    raise response
redis.exceptions.ResponseError: MISCONF Redis is configured to save RDB snapshots, but it's currently unable to persist to disk. Commands that may modify the data set are disabled, because this instance is configured to report errors during writes if RDB snapshotting fails (stop-writes-on-bgsave-error option). Please check the Redis logs for details about the RDB error.

2025-01-06 05:32:40,829 ERROR scheduler Exception in Enqueue Events for Site demo
Traceback (most recent call last):
  File "apps/frappe/frappe/utils/scheduler.py", line 78, in enqueue_events_for_site
    enqueue_events(site=site)
  File "apps/frappe/frappe/utils/scheduler.py", line 96, in enqueue_events
    queued_jobs = get_jobs(site=site, key="job_type").get(site) or []
  File "apps/frappe/frappe/utils/background_jobs.py", line 299, in get_jobs
    jobs = q.jobs + get_running_jobs_in_queue(q)
  File "apps/frappe/frappe/utils/background_jobs.py", line 336, in get_running_jobs_in_queue
    workers = get_workers(queue)
  File "apps/frappe/frappe/utils/background_jobs.py", line 328, in get_workers
    return Worker.all(queue=queue)
  File "env/lib/python3.10/site-packages/rq/worker.py", line 257, in all
    workers = [
  File "env/lib/python3.10/site-packages/rq/worker.py", line 258, in <listcomp>
    cls.find_by_key(
  File "env/lib/python3.10/site-packages/rq/worker.py", line 671, in find_by_key
    connection.srem(cls.redis_workers_keys, worker_key)
  File "env/lib/python3.10/site-packages/redis/client.py", line 2305, in srem
    return self.execute_command('SREM', name, *values)
  File "env/lib/python3.10/site-packages/redis/client.py", line 901, in execute_command
    return self.parse_response(conn, command_name, **options)
  File "env/lib/python3.10/site-packages/redis/client.py", line 915, in parse_response
    response = connection.read_response()
  File "env/lib/python3.10/site-packages/redis/connection.py", line 756, in read_response
    raise response
redis.exceptions.ResponseError: MISCONF Redis is configured to save RDB snapshots, but it's currently unable to persist to disk. Commands that may modify the data set are disabled, because this instance is configured to report errors during writes if RDB snapshotting fails (stop-writes-on-bgsave-error option). Please check the Redis logs for details about the RDB error.

2025-01-06 05:33:40,994 ERROR scheduler Exception in Enqueue Events for Site demo
Traceback (most recent call last):
  File "apps/frappe/frappe/utils/scheduler.py", line 78, in enqueue_events_for_site
    enqueue_events(site=site)
  File "apps/frappe/frappe/utils/scheduler.py", line 96, in enqueue_events
    queued_jobs = get_jobs(site=site, key="job_type").get(site) or []
  File "apps/frappe/frappe/utils/background_jobs.py", line 299, in get_jobs
    jobs = q.jobs + get_running_jobs_in_queue(q)
  File "apps/frappe/frappe/utils/background_jobs.py", line 336, in get_running_jobs_in_queue
    workers = get_workers(queue)
  File "apps/frappe/frappe/utils/background_jobs.py", line 328, in get_workers
    return Worker.all(queue=queue)
  File "env/lib/python3.10/site-packages/rq/worker.py", line 257, in all
    workers = [
  File "env/lib/python3.10/site-packages/rq/worker.py", line 258, in <listcomp>
    cls.find_by_key(
  File "env/lib/python3.10/site-packages/rq/worker.py", line 671, in find_by_key
    connection.srem(cls.redis_workers_keys, worker_key)
  File "env/lib/python3.10/site-packages/redis/client.py", line 2305, in srem
    return self.execute_command('SREM', name, *values)
  File "env/lib/python3.10/site-packages/redis/client.py", line 901, in execute_command
    return self.parse_response(conn, command_name, **options)
  File "env/lib/python3.10/site-packages/redis/client.py", line 915, in parse_response
    response = connection.read_response()
  File "env/lib/python3.10/site-packages/redis/connection.py", line 756, in read_response
    raise response
redis.exceptions.ResponseError: MISCONF Redis is configured to save RDB snapshots, but it's currently unable to persist to disk. Commands that may modify the data set are disabled, because this instance is configured to report errors during writes if RDB snapshotting fails (stop-writes-on-bgsave-error option). Please check the Redis logs for details about the RDB error.

2025-01-06 05:34:41,148 ERROR scheduler Exception in Enqueue Events for Site demo
Traceback (most recent call last):
  File "apps/frappe/frappe/utils/scheduler.py", line 78, in enqueue_events_for_site
    enqueue_events(site=site)
  File "apps/frappe/frappe/utils/scheduler.py", line 96, in enqueue_events
    queued_jobs = get_jobs(site=site, key="job_type").get(site) or []
  File "apps/frappe/frappe/utils/background_jobs.py", line 299, in get_jobs
    jobs = q.jobs + get_running_jobs_in_queue(q)
  File "apps/frappe/frappe/utils/background_jobs.py", line 336, in get_running_jobs_in_queue
    workers = get_workers(queue)
  File "apps/frappe/frappe/utils/background_jobs.py", line 328, in get_workers
    return Worker.all(queue=queue)
  File "env/lib/python3.10/site-packages/rq/worker.py", line 257, in all
    workers = [
  File "env/lib/python3.10/site-packages/rq/worker.py", line 258, in <listcomp>
    cls.find_by_key(
  File "env/lib/python3.10/site-packages/rq/worker.py", line 671, in find_by_key
    connection.srem(cls.redis_workers_keys, worker_key)
  File "env/lib/python3.10/site-packages/redis/client.py", line 2305, in srem
    return self.execute_command('SREM', name, *values)
  File "env/lib/python3.10/site-packages/redis/client.py", line 901, in execute_command
    return self.parse_response(conn, command_name, **options)
  File "env/lib/python3.10/site-packages/redis/client.py", line 915, in parse_response
    response = connection.read_response()
  File "env/lib/python3.10/site-packages/redis/connection.py", line 756, in read_response
    raise response
redis.exceptions.ResponseError: MISCONF Redis is configured to save RDB snapshots, but it's currently unable to persist to disk. Commands that may modify the data set are disabled, because this instance is configured to report errors during writes if RDB snapshotting fails (stop-writes-on-bgsave-error option). Please check the Redis logs for details about the RDB error.

2025-01-06 05:35:41,311 ERROR scheduler Exception in Enqueue Events for Site demo
Traceback (most recent call last):
  File "apps/frappe/frappe/utils/scheduler.py", line 78, in enqueue_events_for_site
    enqueue_events(site=site)
  File "apps/frappe/frappe/utils/scheduler.py", line 96, in enqueue_events
    queued_jobs = get_jobs(site=site, key="job_type").get(site) or []
  File "apps/frappe/frappe/utils/background_jobs.py", line 299, in get_jobs
    jobs = q.jobs + get_running_jobs_in_queue(q)
  File "apps/frappe/frappe/utils/background_jobs.py", line 336, in get_running_jobs_in_queue
    workers = get_workers(queue)
  File "apps/frappe/frappe/utils/background_jobs.py", line 328, in get_workers
    return Worker.all(queue=queue)
  File "env/lib/python3.10/site-packages/rq/worker.py", line 257, in all
    workers = [
  File "env/lib/python3.10/site-packages/rq/worker.py", line 258, in <listcomp>
    cls.find_by_key(
  File "env/lib/python3.10/site-packages/rq/worker.py", line 671, in find_by_key
    connection.srem(cls.redis_workers_keys, worker_key)
  File "env/lib/python3.10/site-packages/redis/client.py", line 2305, in srem
    return self.execute_command('SREM', name, *values)
  File "env/lib/python3.10/site-packages/redis/client.py", line 901, in execute_command
    return self.parse_response(conn, command_name, **options)
  File "env/lib/python3.10/site-packages/redis/client.py", line 915, in parse_response
    response = connection.read_response()
  File "env/lib/python3.10/site-packages/redis/connection.py", line 756, in read_response
    raise response
redis.exceptions.ResponseError: MISCONF Redis is configured to save RDB snapshots, but it's currently unable to persist to disk. Commands that may modify the data set are disabled, because this instance is configured to report errors during writes if RDB snapshotting fails (stop-writes-on-bgsave-error option). Please check the Redis logs for details about the RDB error.

2025-01-07 08:36:34,067 ERROR scheduler Skipped queueing hrms.hr.doctype.interview.interview.send_interview_reminder because it was found in queue for demo
2025-01-07 08:36:34,211 ERROR scheduler Skipped queueing erpnext.stock.doctype.repost_item_valuation.repost_item_valuation.repost_entries because it was found in queue for demo
2025-01-07 08:36:35,082 ERROR scheduler Skipped queueing erpnext.crm.doctype.social_media_post.social_media_post.process_scheduled_social_media_posts because it was found in queue for demo
2025-01-07 08:36:35,443 ERROR scheduler Skipped queueing frappe.monitor.flush because it was found in queue for demo
2025-01-07 08:36:35,451 ERROR scheduler Skipped queueing frappe.utils.global_search.sync_global_search because it was found in queue for demo
2025-01-07 08:36:35,457 ERROR scheduler Skipped queueing frappe.email.doctype.email_account.email_account.notify_unreplied because it was found in queue for demo
2025-01-07 08:36:35,462 ERROR scheduler Skipped queueing frappe.email.queue.flush because it was found in queue for demo
2025-01-07 08:45:21,296 ERROR scheduler Skipped queueing frappe.monitor.flush because it was found in queue for demo
2025-01-07 08:45:21,334 ERROR scheduler Skipped queueing frappe.utils.global_search.sync_global_search because it was found in queue for demo
2025-01-07 08:45:21,342 ERROR scheduler Skipped queueing frappe.email.doctype.email_account.email_account.notify_unreplied because it was found in queue for demo
2025-01-07 08:45:21,354 ERROR scheduler Skipped queueing frappe.email.queue.flush because it was found in queue for demo
2025-01-07 08:45:21,384 ERROR scheduler Skipped queueing frappe.twofactor.delete_all_barcodes_for_users because it was found in queue for demo
2025-01-07 08:45:21,393 ERROR scheduler Skipped queueing frappe.website.doctype.web_page.web_page.check_publish_status because it was found in queue for demo
2025-01-07 08:45:21,404 ERROR scheduler Skipped queueing frappe.oauth.delete_oauth2_data because it was found in queue for demo
2025-01-07 08:46:22,796 ERROR scheduler Skipped queueing hrms.hr.doctype.interview.interview.send_interview_reminder because it was found in queue for demo
2025-01-07 08:46:22,944 ERROR scheduler Skipped queueing erpnext.crm.doctype.social_media_post.social_media_post.process_scheduled_social_media_posts because it was found in queue for demo
2025-01-07 08:46:23,132 ERROR scheduler Skipped queueing frappe.monitor.flush because it was found in queue for demo
2025-01-07 08:46:23,139 ERROR scheduler Skipped queueing frappe.utils.global_search.sync_global_search because it was found in queue for demo
2025-01-07 08:46:23,144 ERROR scheduler Skipped queueing frappe.email.doctype.email_account.email_account.notify_unreplied because it was found in queue for demo
2025-01-07 08:46:23,149 ERROR scheduler Skipped queueing frappe.email.queue.flush because it was found in queue for demo
2025-01-07 08:51:54,490 ERROR scheduler Skipped queueing hrms.hr.doctype.interview.interview.send_interview_reminder because it was found in queue for demo
2025-01-07 08:51:54,891 ERROR scheduler Skipped queueing erpnext.crm.doctype.social_media_post.social_media_post.process_scheduled_social_media_posts because it was found in queue for demo
2025-01-07 08:51:55,396 ERROR scheduler Skipped queueing frappe.monitor.flush because it was found in queue for demo
2025-01-07 08:51:55,403 ERROR scheduler Skipped queueing frappe.utils.global_search.sync_global_search because it was found in queue for demo
2025-01-07 08:51:55,417 ERROR scheduler Skipped queueing frappe.email.doctype.email_account.email_account.notify_unreplied because it was found in queue for demo
2025-01-07 08:51:55,431 ERROR scheduler Skipped queueing frappe.email.queue.flush because it was found in queue for demo
2025-01-07 08:51:55,449 ERROR scheduler Skipped queueing frappe.email.doctype.email_account.email_account.pull because it was found in queue for demo
2025-01-07 08:58:17,309 ERROR scheduler Skipped queueing hrms.hr.doctype.interview.interview.send_interview_reminder because it was found in queue for demo
2025-01-07 08:58:18,224 ERROR scheduler Skipped queueing erpnext.crm.doctype.social_media_post.social_media_post.process_scheduled_social_media_posts because it was found in queue for demo
2025-01-07 08:58:18,498 ERROR scheduler Skipped queueing frappe.monitor.flush because it was found in queue for demo
2025-01-07 08:58:18,504 ERROR scheduler Skipped queueing frappe.utils.global_search.sync_global_search because it was found in queue for demo
2025-01-07 08:58:18,514 ERROR scheduler Skipped queueing frappe.email.doctype.email_account.email_account.notify_unreplied because it was found in queue for demo
2025-01-07 08:58:18,525 ERROR scheduler Skipped queueing frappe.email.queue.flush because it was found in queue for demo
2025-01-07 09:01:11,890 ERROR scheduler Skipped queueing erpnext.utilities.doctype.video.video.update_youtube_data because it was found in queue for demo
2025-01-07 09:01:11,954 ERROR scheduler Skipped queueing erpnext.accounts.doctype.process_payment_reconciliation.process_payment_reconciliation.trigger_reconciliation_for_queued_docs because it was found in queue for demo
2025-01-07 09:01:11,981 ERROR scheduler Skipped queueing erpnext.manufacturing.doctype.bom_update_log.bom_update_log.resume_bom_cost_update_jobs because it was found in queue for demo
2025-01-07 09:01:12,225 ERROR scheduler Skipped queueing frappe.email.doctype.email_account.email_account.pull because it was found in queue for demo
2025-01-07 09:01:12,235 ERROR scheduler Skipped queueing frappe.twofactor.delete_all_barcodes_for_users because it was found in queue for demo
2025-01-07 09:01:12,247 ERROR scheduler Skipped queueing frappe.website.doctype.web_page.web_page.check_publish_status because it was found in queue for demo
2025-01-07 09:01:12,254 ERROR scheduler Skipped queueing frappe.oauth.delete_oauth2_data because it was found in queue for demo
2025-01-07 09:05:51,250 ERROR scheduler Skipped queueing erpnext.crm.doctype.social_media_post.social_media_post.process_scheduled_social_media_posts because it was found in queue for demo
2025-01-07 09:05:51,615 ERROR scheduler Skipped queueing frappe.monitor.flush because it was found in queue for demo
2025-01-07 09:05:51,639 ERROR scheduler Skipped queueing frappe.utils.global_search.sync_global_search because it was found in queue for demo
2025-01-07 09:05:51,683 ERROR scheduler Skipped queueing frappe.email.queue.flush because it was found in queue for demo
2025-01-07 09:05:51,702 ERROR scheduler Skipped queueing frappe.email.doctype.email_account.email_account.pull because it was found in queue for demo
2025-01-07 09:17:20,166 ERROR scheduler Exception in Enqueue Events for Site demo
Traceback (most recent call last):
  File "apps/frappe/frappe/utils/scheduler.py", line 78, in enqueue_events_for_site
    enqueue_events(site=site)
  File "apps/frappe/frappe/utils/scheduler.py", line 101, in enqueue_events
    frappe.get_doc("Scheduled Job Type", job_type.name).enqueue()
  File "apps/frappe/frappe/__init__.py", line 1200, in get_doc
    doc = frappe.model.document.get_doc(*args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 78, in get_doc
    return controller(*args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 110, in __init__
    self.load_from_db()
  File "apps/frappe/frappe/model/document.py", line 149, in load_from_db
    d = frappe.db.get_value(self.doctype, self.name, "*", as_dict=1, for_update=self.flags.for_update)
  File "apps/frappe/frappe/database/database.py", line 568, in get_value
    result = self.get_values(
  File "apps/frappe/frappe/database/database.py", line 672, in get_values
    out = self._get_values_from_table(
  File "apps/frappe/frappe/database/database.py", line 910, in _get_values_from_table
    return query.run(as_dict=as_dict, debug=debug, update=update, run=run, pluck=pluck)
  File "apps/frappe/frappe/query_builder/utils.py", line 87, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
  File "apps/frappe/frappe/database/database.py", line 244, in sql
    self._cursor.execute(query, values)
  File "env/lib/python3.10/site-packages/pymysql/cursors.py", line 153, in execute
    result = self._query(query)
  File "env/lib/python3.10/site-packages/pymysql/cursors.py", line 322, in _query
    conn.query(q)
  File "env/lib/python3.10/site-packages/pymysql/connections.py", line 563, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "env/lib/python3.10/site-packages/pymysql/connections.py", line 825, in _read_query_result
    result.read()
  File "env/lib/python3.10/site-packages/pymysql/connections.py", line 1199, in read
    first_packet = self.connection._read_packet()
  File "env/lib/python3.10/site-packages/pymysql/connections.py", line 744, in _read_packet
    packet_header = self._read_bytes(4)
  File "env/lib/python3.10/site-packages/pymysql/connections.py", line 798, in _read_bytes
    raise err.OperationalError(
pymysql.err.OperationalError: (2013, 'Lost connection to MySQL server during query')

2025-01-07 09:17:20,681 ERROR scheduler Exception in Enqueue Events for Site demo
Traceback (most recent call last):
  File "apps/frappe/frappe/utils/scheduler.py", line 78, in enqueue_events_for_site
    enqueue_events(site=site)
  File "apps/frappe/frappe/utils/scheduler.py", line 101, in enqueue_events
    frappe.get_doc("Scheduled Job Type", job_type.name).enqueue()
  File "apps/frappe/frappe/__init__.py", line 1200, in get_doc
    doc = frappe.model.document.get_doc(*args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 78, in get_doc
    return controller(*args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 110, in __init__
    self.load_from_db()
  File "apps/frappe/frappe/model/document.py", line 149, in load_from_db
    d = frappe.db.get_value(self.doctype, self.name, "*", as_dict=1, for_update=self.flags.for_update)
  File "apps/frappe/frappe/database/database.py", line 568, in get_value
    result = self.get_values(
  File "apps/frappe/frappe/database/database.py", line 672, in get_values
    out = self._get_values_from_table(
  File "apps/frappe/frappe/database/database.py", line 910, in _get_values_from_table
    return query.run(as_dict=as_dict, debug=debug, update=update, run=run, pluck=pluck)
  File "apps/frappe/frappe/query_builder/utils.py", line 87, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
  File "apps/frappe/frappe/database/database.py", line 244, in sql
    self._cursor.execute(query, values)
  File "env/lib/python3.10/site-packages/pymysql/cursors.py", line 153, in execute
    result = self._query(query)
  File "env/lib/python3.10/site-packages/pymysql/cursors.py", line 322, in _query
    conn.query(q)
  File "env/lib/python3.10/site-packages/pymysql/connections.py", line 563, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "env/lib/python3.10/site-packages/pymysql/connections.py", line 825, in _read_query_result
    result.read()
  File "env/lib/python3.10/site-packages/pymysql/connections.py", line 1199, in read
    first_packet = self.connection._read_packet()
  File "env/lib/python3.10/site-packages/pymysql/connections.py", line 744, in _read_packet
    packet_header = self._read_bytes(4)
  File "env/lib/python3.10/site-packages/pymysql/connections.py", line 798, in _read_bytes
    raise err.OperationalError(
pymysql.err.OperationalError: (2013, 'Lost connection to MySQL server during query')

2025-01-07 09:18:56,410 ERROR scheduler Exception in Enqueue Events for Site demo
Traceback (most recent call last):
  File "env/lib/python3.10/site-packages/pymysql/connections.py", line 649, in connect
    sock = socket.create_connection(
  File "/usr/lib/python3.10/socket.py", line 857, in create_connection
    raise err
  File "/usr/lib/python3.10/socket.py", line 845, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "apps/frappe/frappe/utils/scheduler.py", line 75, in enqueue_events_for_site
    if is_scheduler_inactive():
  File "apps/frappe/frappe/utils/scheduler.py", line 119, in is_scheduler_inactive
    if is_scheduler_disabled(verbose=verbose):
  File "apps/frappe/frappe/utils/scheduler.py", line 132, in is_scheduler_disabled
    frappe.db.get_single_value("System Settings", "enable_scheduler")
  File "apps/frappe/frappe/database/database.py", line 859, in get_single_value
    ).run()
  File "apps/frappe/frappe/query_builder/utils.py", line 87, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
  File "apps/frappe/frappe/database/database.py", line 221, in sql
    self.connect()
  File "apps/frappe/frappe/database/database.py", line 126, in connect
    self._conn: "MariadbConnection" | "PostgresConnection" = self.get_connection()
  File "apps/frappe/frappe/database/mariadb/database.py", line 103, in get_connection
    conn = self._get_connection()
  File "apps/frappe/frappe/database/mariadb/database.py", line 109, in _get_connection
    return self.create_connection()
  File "apps/frappe/frappe/database/mariadb/database.py", line 112, in create_connection
    return pymysql.connect(**self.get_connection_settings())
  File "env/lib/python3.10/site-packages/pymysql/connections.py", line 361, in __init__
    self.connect()
  File "env/lib/python3.10/site-packages/pymysql/connections.py", line 716, in connect
    raise exc
pymysql.err.OperationalError: (2003, "Can't connect to MySQL server on '127.0.0.1' ([Errno 111] Connection refused)")

2025-01-07 09:18:56,411 ERROR scheduler Exception in Enqueue Events for Site demo
Traceback (most recent call last):
  File "env/lib/python3.10/site-packages/pymysql/connections.py", line 649, in connect
    sock = socket.create_connection(
  File "/usr/lib/python3.10/socket.py", line 857, in create_connection
    raise err
  File "/usr/lib/python3.10/socket.py", line 845, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "apps/frappe/frappe/utils/scheduler.py", line 75, in enqueue_events_for_site
    if is_scheduler_inactive():
  File "apps/frappe/frappe/utils/scheduler.py", line 119, in is_scheduler_inactive
    if is_scheduler_disabled(verbose=verbose):
  File "apps/frappe/frappe/utils/scheduler.py", line 132, in is_scheduler_disabled
    frappe.db.get_single_value("System Settings", "enable_scheduler")
  File "apps/frappe/frappe/database/database.py", line 859, in get_single_value
    ).run()
  File "apps/frappe/frappe/query_builder/utils.py", line 87, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
  File "apps/frappe/frappe/database/database.py", line 221, in sql
    self.connect()
  File "apps/frappe/frappe/database/database.py", line 126, in connect
    self._conn: "MariadbConnection" | "PostgresConnection" = self.get_connection()
  File "apps/frappe/frappe/database/mariadb/database.py", line 103, in get_connection
    conn = self._get_connection()
  File "apps/frappe/frappe/database/mariadb/database.py", line 109, in _get_connection
    return self.create_connection()
  File "apps/frappe/frappe/database/mariadb/database.py", line 112, in create_connection
    return pymysql.connect(**self.get_connection_settings())
  File "env/lib/python3.10/site-packages/pymysql/connections.py", line 361, in __init__
    self.connect()
  File "env/lib/python3.10/site-packages/pymysql/connections.py", line 716, in connect
    raise exc
pymysql.err.OperationalError: (2003, "Can't connect to MySQL server on '127.0.0.1' ([Errno 111] Connection refused)")

2025-01-07 09:23:26,129 ERROR scheduler Skipped queueing erpnext.crm.doctype.social_media_post.social_media_post.process_scheduled_social_media_posts because it was found in queue for demo
2025-01-07 09:23:26,250 ERROR scheduler Skipped queueing erpnext.accounts.doctype.process_payment_reconciliation.process_payment_reconciliation.trigger_reconciliation_for_queued_docs because it was found in queue for demo
2025-01-07 09:23:26,259 ERROR scheduler Skipped queueing erpnext.manufacturing.doctype.bom_update_log.bom_update_log.resume_bom_cost_update_jobs because it was found in queue for demo
2025-01-07 09:23:26,755 ERROR scheduler Skipped queueing frappe.monitor.flush because it was found in queue for demo
2025-01-07 09:23:26,777 ERROR scheduler Skipped queueing frappe.utils.global_search.sync_global_search because it was found in queue for demo
2025-01-07 09:23:26,783 ERROR scheduler Skipped queueing frappe.email.doctype.email_account.email_account.notify_unreplied because it was found in queue for demo
2025-01-07 09:23:26,814 ERROR scheduler Skipped queueing frappe.email.queue.flush because it was found in queue for demo
2025-01-07 09:23:26,880 ERROR scheduler Skipped queueing frappe.email.doctype.email_account.email_account.pull because it was found in queue for demo
2025-01-07 09:23:26,895 ERROR scheduler Skipped queueing frappe.twofactor.delete_all_barcodes_for_users because it was found in queue for demo
2025-01-07 09:23:26,914 ERROR scheduler Skipped queueing frappe.website.doctype.web_page.web_page.check_publish_status because it was found in queue for demo
2025-01-07 09:23:26,939 ERROR scheduler Skipped queueing frappe.oauth.delete_oauth2_data because it was found in queue for demo
2025-01-07 09:26:30,294 ERROR scheduler Skipped queueing erpnext.crm.doctype.social_media_post.social_media_post.process_scheduled_social_media_posts because it was found in queue for demo
2025-01-07 09:26:30,472 ERROR scheduler Skipped queueing frappe.monitor.flush because it was found in queue for demo
2025-01-07 09:26:30,480 ERROR scheduler Skipped queueing frappe.utils.global_search.sync_global_search because it was found in queue for demo
2025-01-07 09:26:30,487 ERROR scheduler Skipped queueing frappe.email.doctype.email_account.email_account.notify_unreplied because it was found in queue for demo
2025-01-07 09:26:30,492 ERROR scheduler Skipped queueing frappe.email.queue.flush because it was found in queue for demo
2025-01-07 09:30:32,293 ERROR scheduler Skipped queueing hrms.hr.doctype.daily_work_summary_group.daily_work_summary_group.trigger_emails because it was found in queue for demo
2025-01-07 09:30:32,309 ERROR scheduler Skipped queueing hrms.hr.doctype.interview.interview.send_interview_reminder because it was found in queue for demo
2025-01-07 09:30:32,404 ERROR scheduler Skipped queueing erpnext.projects.doctype.project.project.collect_project_status because it was found in queue for demo
2025-01-07 09:30:32,410 ERROR scheduler Skipped queueing erpnext.projects.doctype.project.project.hourly_reminder because it was found in queue for demo
2025-01-07 09:30:32,416 ERROR scheduler Skipped queueing erpnext.projects.doctype.project.project.project_status_update_reminder because it was found in queue for demo
2025-01-07 09:30:32,420 ERROR scheduler Skipped queueing erpnext.erpnext_integrations.doctype.plaid_settings.plaid_settings.automatic_synchronization because it was found in queue for demo
2025-01-07 09:30:32,425 ERROR scheduler Skipped queueing erpnext.crm.doctype.social_media_post.social_media_post.process_scheduled_social_media_posts because it was found in queue for demo
2025-01-07 09:30:32,433 ERROR scheduler Skipped queueing erpnext.utilities.doctype.video.video.update_youtube_data because it was found in queue for demo
2025-01-07 09:30:32,440 ERROR scheduler Skipped queueing erpnext.accounts.doctype.process_payment_reconciliation.process_payment_reconciliation.trigger_reconciliation_for_queued_docs because it was found in queue for demo
2025-01-07 09:30:32,445 ERROR scheduler Skipped queueing erpnext.manufacturing.doctype.bom_update_log.bom_update_log.resume_bom_cost_update_jobs because it was found in queue for demo
2025-01-07 09:30:32,519 ERROR scheduler Skipped queueing frappe.website.doctype.personal_data_deletion_request.personal_data_deletion_request.process_data_deletion_request because it was found in queue for demo
2025-01-07 09:30:32,523 ERROR scheduler Skipped queueing frappe.email.doctype.newsletter.newsletter.send_scheduled_email because it was found in queue for demo
2025-01-07 09:30:32,528 ERROR scheduler Skipped queueing frappe.integrations.doctype.google_calendar.google_calendar.sync because it was found in queue for demo
2025-01-07 09:30:32,533 ERROR scheduler Skipped queueing frappe.desk.form.document_follow.send_hourly_updates because it was found in queue for demo
2025-01-07 09:30:32,537 ERROR scheduler Skipped queueing frappe.deferred_insert.save_to_db because it was found in queue for demo
2025-01-07 09:30:32,541 ERROR scheduler Skipped queueing frappe.desk.page.backups.backups.delete_downloadable_backups because it was found in queue for demo
2025-01-07 09:30:32,544 ERROR scheduler Skipped queueing frappe.utils.error.collect_error_snapshots because it was found in queue for demo
2025-01-07 09:30:32,549 ERROR scheduler Skipped queueing frappe.model.utils.user_settings.sync_user_settings because it was found in queue for demo
2025-01-07 09:30:32,554 ERROR scheduler Skipped queueing frappe.model.utils.link_count.update_link_count because it was found in queue for demo
2025-01-07 09:30:32,558 ERROR scheduler Skipped queueing frappe.monitor.flush because it was found in queue for demo
2025-01-07 09:30:32,562 ERROR scheduler Skipped queueing frappe.utils.global_search.sync_global_search because it was found in queue for demo
2025-01-07 09:30:32,566 ERROR scheduler Skipped queueing frappe.email.doctype.email_account.email_account.notify_unreplied because it was found in queue for demo
2025-01-07 09:30:32,570 ERROR scheduler Skipped queueing frappe.email.queue.flush because it was found in queue for demo
2025-01-07 09:30:32,576 ERROR scheduler Skipped queueing frappe.email.doctype.email_account.email_account.pull because it was found in queue for demo
2025-01-07 09:30:32,582 ERROR scheduler Skipped queueing frappe.twofactor.delete_all_barcodes_for_users because it was found in queue for demo
2025-01-07 09:30:32,586 ERROR scheduler Skipped queueing frappe.website.doctype.web_page.web_page.check_publish_status because it was found in queue for demo
2025-01-07 09:30:32,590 ERROR scheduler Skipped queueing frappe.oauth.delete_oauth2_data because it was found in queue for demo
2025-01-07 09:31:32,730 ERROR scheduler Skipped queueing hrms.hr.doctype.shift_type.shift_type.process_auto_attendance_for_all_shifts because it was found in queue for demo
2025-01-07 09:36:48,401 ERROR scheduler Skipped queueing hrms.hr.doctype.interview.interview.send_interview_reminder because it was found in queue for demo
2025-01-07 09:36:48,649 ERROR scheduler Skipped queueing erpnext.crm.doctype.social_media_post.social_media_post.process_scheduled_social_media_posts because it was found in queue for demo
2025-01-07 09:36:49,033 ERROR scheduler Skipped queueing frappe.monitor.flush because it was found in queue for demo
2025-01-07 09:36:49,041 ERROR scheduler Skipped queueing frappe.utils.global_search.sync_global_search because it was found in queue for demo
2025-01-07 09:36:49,048 ERROR scheduler Skipped queueing frappe.email.doctype.email_account.email_account.notify_unreplied because it was found in queue for demo
2025-01-07 09:36:49,054 ERROR scheduler Skipped queueing frappe.email.queue.flush because it was found in queue for demo
2025-01-07 09:39:39,754 ERROR scheduler Skipped queueing hrms.hr.doctype.interview.interview.send_interview_reminder because it was found in queue for demo
2025-01-07 09:39:40,488 ERROR scheduler Skipped queueing frappe.monitor.flush because it was found in queue for demo
2025-01-07 09:40:41,012 ERROR scheduler Skipped queueing frappe.email.doctype.email_account.email_account.pull because it was found in queue for demo
2025-01-07 09:42:41,818 ERROR scheduler Skipped queueing hrms.hr.doctype.interview.interview.send_interview_reminder because it was found in queue for demo
2025-01-07 09:42:41,934 ERROR scheduler Skipped queueing erpnext.crm.doctype.social_media_post.social_media_post.process_scheduled_social_media_posts because it was found in queue for demo
2025-01-07 09:42:42,095 ERROR scheduler Skipped queueing frappe.monitor.flush because it was found in queue for demo
2025-01-07 09:42:42,100 ERROR scheduler Skipped queueing frappe.utils.global_search.sync_global_search because it was found in queue for demo
2025-01-07 09:42:42,104 ERROR scheduler Skipped queueing frappe.email.doctype.email_account.email_account.notify_unreplied because it was found in queue for demo
2025-01-07 09:42:42,108 ERROR scheduler Skipped queueing frappe.email.queue.flush because it was found in queue for demo
2025-01-07 09:45:45,470 ERROR scheduler Skipped queueing erpnext.accounts.doctype.process_payment_reconciliation.process_payment_reconciliation.trigger_reconciliation_for_queued_docs because it was found in queue for demo
2025-01-07 09:45:45,528 ERROR scheduler Skipped queueing erpnext.manufacturing.doctype.bom_update_log.bom_update_log.resume_bom_cost_update_jobs because it was found in queue for demo
2025-01-07 09:45:45,747 ERROR scheduler Skipped queueing frappe.twofactor.delete_all_barcodes_for_users because it was found in queue for demo
2025-01-07 09:45:45,753 ERROR scheduler Skipped queueing frappe.website.doctype.web_page.web_page.check_publish_status because it was found in queue for demo
2025-01-07 09:45:45,759 ERROR scheduler Skipped queueing frappe.oauth.delete_oauth2_data because it was found in queue for demo
2025-01-08 07:27:23,558 ERROR scheduler Skipped queueing erpnext.crm.doctype.social_media_post.social_media_post.process_scheduled_social_media_posts because it was found in queue for demo
2025-01-08 09:14:06,339 ERROR scheduler Skipped queueing erpnext.crm.doctype.social_media_post.social_media_post.process_scheduled_social_media_posts because it was found in queue for demo
2025-01-08 09:14:06,581 ERROR scheduler Skipped queueing frappe.monitor.flush because it was found in queue for demo
2025-01-08 09:14:06,588 ERROR scheduler Skipped queueing frappe.utils.global_search.sync_global_search because it was found in queue for demo
2025-01-08 09:14:06,598 ERROR scheduler Skipped queueing frappe.email.doctype.email_account.email_account.notify_unreplied because it was found in queue for demo
2025-01-08 09:14:06,605 ERROR scheduler Skipped queueing frappe.email.queue.flush because it was found in queue for demo
2025-01-09 04:35:43,856 ERROR scheduler Skipped queueing hrms.hr.doctype.interview.interview.send_interview_reminder because it was found in queue for demo
2025-01-09 04:35:44,233 ERROR scheduler Skipped queueing erpnext.crm.doctype.social_media_post.social_media_post.process_scheduled_social_media_posts because it was found in queue for demo
2025-01-09 04:35:44,559 ERROR scheduler Skipped queueing frappe.monitor.flush because it was found in queue for demo
2025-01-09 04:35:44,566 ERROR scheduler Skipped queueing frappe.utils.global_search.sync_global_search because it was found in queue for demo
2025-01-09 04:35:44,575 ERROR scheduler Skipped queueing frappe.email.doctype.email_account.email_account.notify_unreplied because it was found in queue for demo
2025-01-09 04:35:44,580 ERROR scheduler Skipped queueing frappe.email.queue.flush because it was found in queue for demo
2025-01-09 04:38:56,604 ERROR scheduler Skipped queueing hrms.hr.doctype.interview.interview.send_interview_reminder because it was found in queue for demo
2025-01-09 04:38:56,748 ERROR scheduler Skipped queueing erpnext.crm.doctype.social_media_post.social_media_post.process_scheduled_social_media_posts because it was found in queue for demo
2025-01-09 04:38:56,883 ERROR scheduler Skipped queueing frappe.monitor.flush because it was found in queue for demo
2025-01-09 04:38:56,888 ERROR scheduler Skipped queueing frappe.utils.global_search.sync_global_search because it was found in queue for demo
2025-01-09 04:38:56,893 ERROR scheduler Skipped queueing frappe.email.doctype.email_account.email_account.notify_unreplied because it was found in queue for demo
2025-01-09 04:38:56,898 ERROR scheduler Skipped queueing frappe.email.queue.flush because it was found in queue for demo
